---

- name: ALERTMANAGER | Ensure alertmanager group
  group:
    name: "{{ alertmanager_group }}"
    system: yes
    state: present

- name: ALERTMANAGER | Ensure alertmanager user
  user:
    name: "{{ alertmanager_user }}"
    group: "{{ alertmanager_group }}"
    system: yes
    shell: /usr/sbin/nologin
    createhome: no

- name: ALERTMANAGER | Ensure skeleton paths
  file:
    dest: "{{ item }}"
    owner: "{{ alertmanager_user }}"
    group: "{{ alertmanager_user }}"
    state: directory
  with_items:
    - "{{ alertmanager_root_path }}"
    - "{{ alertmanager_conf_path }}"
    - "{{ alertmanager_conf_path }}/parts"
    - "{{ alertmanager_templates_path }}"
    - "{{ alertmanager_bin_path }}"
    - "{{ alertmanager_log_path }}"

- name: ALERTMANAGER | Use -- as option-bullet
  set_fact:
    option_bullet: "--"
  when: alertmanager_version is version('0.12', '>=')

- name: ALERTMANAGER | Use - as option-bullet
  set_fact:
    option_bullet: "-"
  when: alertmanager_version is version('0.12', '<')

- name: ALERTMANAGER | Check alertmanager version
  command: alertmanager {{ option_bullet }}version
  register: alertmanager_check
  changed_when: no
  ignore_errors: yes

- name: ALERTMANAGER | Check if installation is needed
  set_fact:
    alertmanager_install: >-
      {{
      alertmanager_check is failed or (
      'alertmanager, version ' + alertmanager_version not in alertmanager_check.stdout and
      'alertmanager, version ' + alertmanager_version not in alertmanager_check.stderr
      )
      }}

- name: ALERTMANAGER | Download package
  get_url:
    url: "{{ alertmanager_url }}"
    dest: /tmp
  when: alertmanager_install or alertmanager_force_reinstall

- name: ALERTMANAGER | Extract package
  unarchive:
    copy: no
    src: "/tmp/{{ alertmanager_package }}"
    dest: /tmp
  when: alertmanager_install or alertmanager_force_reinstall

- name: ALERTMANAGER | Copy binary
  copy:
    src: "/tmp/{{ alertmanager_release_name }}/alertmanager"
    dest: "{{ alertmanager_bin_path }}/alertmanager"
    owner: "{{ alertmanager_user }}"
    group: "{{ alertmanager_group }}"
    remote_src: True
    mode: 0755
  when: alertmanager_install or alertmanager_force_reinstall
  notify: restart alertmanager

- name: ALERTMANAGER | Link binary
  file:
    src: "{{ alertmanager_bin_path }}/alertmanager"
    dest: "/usr/bin/alertmanager"
    state: link

- name: ALERTMANAGER | Copy Daemon script
  template:
    src: alertmanager.service.j2
    dest: /lib/systemd/system/alertmanager.service
    mode: 0644
  notify: restart alertmanager
